# Project The counterfeit detection

In [81]:
import os
import re
import warnings

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from catboost import CatBoostClassifier, Pool
from IPython.display import display, HTML
from sklearn import set_config
from sklearn.dummy import DummyClassifier
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    f1_score,
    classification_report
)
from sklearn.model_selection import (
    train_test_split,
)
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import (
    LabelEncoder,
    MinMaxScaler,
    OneHotEncoder,
    RobustScaler,
    StandardScaler,
)
from torch.utils.data import DataLoader
from torchvision import transforms

import config
from src.data_loader import (
    load_data,
    train_val_test_split,
    ImageDataset)
from src.features import ImageFeatureExtractor, SentenceEmbedder
from src.preprocessing import TabularPreprocessor, TextPreprocessor
from src.utils import preview_batch, create_resized_dataset
from src.multimodal import MultiModalFeatureUnion
from src.model import MultiModalClassifier

In [82]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

## Загрузка данных

In [3]:
data = load_data(config.DATA_CSV)

In [4]:
data.shape

(197198, 44)

In [5]:
data.head(5)

,resolution,brand_name,description,name_rus,commercial_type_name4,rating_1_count,rating_2_count,rating_3_count,rating_4_count,rating_5_count,...,exemplar_returned_count_total30,exemplar_returned_count_total90,exemplar_returned_value_total7,exemplar_returned_value_total30,exemplar_returned_value_total90,item_variety_count,item_available_count,seller_time_alive,item_id,seller_id
id,,,,,,,,,,,,,,,,,,,,,
159385,0,ACTRUM,"Мешки пылесборники для пылесоса PHILIPS, 10 шт...","Мешки для пылесоса PHILIPS TRIATLON, синтетиче...",Пылесборник,6.0,4.0,4.0,3.0,32.0,...,11.0,50.0,730.171845,896.528847,1043.118191,1.0,1.0,1860.0,78312,1218
288616,0,Red Line,Защитная силиконовая крышка обьектива GoPro He...,Защитная крышка Redline на экшн-камеру GoPro (...,Крышка для объектива,NaN,NaN,NaN,NaN,NaN,...,26.0,54.0,993.043882,1137.421611,1188.608000,1.0,1.0,1757.0,141999,1374
108090,0,Talwar Brothers,Плоский медиатор из кости толщиной 0.6 мм<br/>...,Медиатор для гитары Acura GP-PB6,Аксессуар для музыкального инструмента,0.0,0.0,1.0,0.0,1.0,...,16.0,34.0,800.822138,1174.069505,1224.798286,1.0,1.0,1722.0,53306,1448
415607,0,NaN,"Игра Sonic Frontiers для PlayStation 5, русски...","Игра Sonic Frontiers для PlayStation 5, русски...",Видеоигра,NaN,NaN,NaN,NaN,NaN,...,3.0,6.0,0.000000,913.530121,982.789171,3.0,3.0,1692.0,202599,715
332391,0,NaN,Disney Classic Games: Aladdin and The Lion Kin...,"Игра Aladdin and Lion King (PlayStation 4, анг...",Видеоигра,1.0,0.0,0.0,0.0,0.0,...,3.0,6.0,0.000000,913.542170,982.783783,3.0,3.0,1692.0,163725,715

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 197198 entries, 159385 to 104566
Data columns (total 44 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   resolution                       197198 non-null  int64
 1   brand_name                       116667 non-null  object
 2   description                      171138 non-null  object
 3   name_rus                         197198 non-null  object
 4   commercial_type_name4            197198 non-null  object
 5   rating_1_count                   47193 non-null   float64
 6   rating_2_count                   47193 non-null   float64
 7   rating_3_count                   47193 non-null   float64
 8   rating_4_count                   47193 non-null   float64
 9   rating_5_count                   47193 non-null   float64
 10  comments_published_count         47193 non-null   float64
 11  photos_published_count           47193 non-null   float64
 12  videos_published_count           47193 non-null   float64
 13  price_discounted                 197198 non-null  float64
 14  item_time_alive                  197198 non-null  int64
 15  item_count_fake_returns7         197198 non-null  int64
 16  item_count_fake_returns30        197198 non-null  int64
 17  item_count_fake_returns90        197198 non-null  int64
 18  item_count_sales7                197198 non-null  int64
 19  item_count_sales30               197198 non-null  int64
 20  item_count_sales90               197198 non-null  int64
 21  item_count_returns7              197198 non-null  int64
 22  item_count_returns30             197198 non-null  int64
 23  item_count_returns90             197198 non-null  int64
 24  gmv_total7                       187007 non-null  float64
 25  gmv_total30                      189268 non-null  float64
 26  gmv_total90                      189791 non-null  float64
 27  exemplar_accepted_count_total7   187007 non-null  float64
 28  exemplar_accepted_count_total30  189268 non-null  float64
 29  exemplar_accepted_count_total90  189791 non-null  float64
 30  order_accepted_count_total7      186797 non-null  float64
 31  order_accepted_count_total30     189038 non-null  float64
 32  order_accepted_count_total90     189681 non-null  float64
 33  exemplar_returned_count_total7   187007 non-null  float64
 34  exemplar_returned_count_total30  189268 non-null  float64
 35  exemplar_returned_count_total90  189791 non-null  float64
 36  exemplar_returned_value_total7   187007 non-null  float64
 37  exemplar_returned_value_total30  189268 non-null  float64
 38  exemplar_returned_value_total90  189791 non-null  float64
 39  item_variety_count               196201 non-null  float64
 40  item_available_count             196201 non-null  float64
 41  seller_time_alive                197198 non-null  float64
 42  item_id                          197198 non-null  int64
 43  seller_id                        197198 non-null  int64
dtypes: float64(27), int64(13), object(4)
memory usage: 67.7+ MB

## Разделение на трейн, валид, тест

In [7]:
# УДАЛИТЬ ПЕРЕД ВЫГРУЗКОЙ
data = data.sample(n=10000, random_state=config.SEED)
data.shape

(10000, 44)

In [8]:
train_df, val_df, test_df, y_train, y_test, y_val = train_val_test_split(
    data, test_size=config.TEST_SIZE, val_size=config.VAL_SIZE, random_state=config.SEED
)

In [9]:
train_df.shape, val_df.shape, test_df.shape

((5000, 43), (2500, 43), (2500, 43))

## Предобработка. Извлечение фич из картинок и описаний

In [10]:
multimodal = MultiModalFeatureUnion()
multimodal

MultiModalFeatureUnion()

In [11]:
multimodal.fit(train_df)

Обнаружено категориальных признаков: 14
Обнаружено числовых признаков: 26
Загрузка модели из кэша model_cache\all-MiniLM-L6-v2
Модель загружена из кэша
Загрузка модели из кэша model_cache\resnet50\model_weights.pth
Препроцессоры обучены

MultiModalFeatureUnion()

In [12]:
comb_train = multimodal.transform(train_df)
comb_train.head(3)

Извлечение эмбеддингов для 5000 текстов...

Batches:   0%|          | 0/40 [00:00<?, ?it/s]

Получены эмбеддинги: (5000, 384)
...Извлечение признаков из изображений...

Batches:   0%|          | 0/313 [00:00<?, ?it/s]

Извлечено 5000 признаков размерностью 2048
Извлечены признаки: (5000, 2472)

,comments_published_count,exemplar_accepted_count_total30,exemplar_accepted_count_total7,exemplar_accepted_count_total90,exemplar_returned_count_total30,exemplar_returned_count_total7,exemplar_returned_count_total90,exemplar_returned_value_total30,exemplar_returned_value_total7,exemplar_returned_value_total90,...,img_emb_2038,img_emb_2039,img_emb_2040,img_emb_2041,img_emb_2042,img_emb_2043,img_emb_2044,img_emb_2045,img_emb_2046,img_emb_2047
192916,0.0,1810.0,474.0,5809.0,75.0,30.0,261.0,1132.373215,1054.105798,1251.093806,...,0.285511,0.545595,0.170676,0.381655,1.299194,0.405111,0.638620,0.077434,0.396986,0.209114
84511,0.0,21.0,6.0,62.0,0.0,0.0,2.0,0.000000,0.000000,817.196691,...,0.563394,0.208234,0.500127,0.027349,0.468975,0.023563,0.271265,0.005050,0.046967,0.460535
71384,20.0,71.0,28.0,75.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,...,0.666684,0.885570,0.541079,0.328504,0.280005,0.252562,0.098060,0.065360,0.007345,0.266001

In [13]:
comb_val = multimodal.transform(val_df)
comb_val.head(3)

Извлечение эмбеддингов для 2500 текстов...

Batches:   0%|          | 0/20 [00:00<?, ?it/s]

Получены эмбеддинги: (2500, 384)
...Извлечение признаков из изображений...

Batches:   0%|          | 0/157 [00:00<?, ?it/s]

Извлечено 2500 признаков размерностью 2048
Извлечены признаки: (2500, 2472)

,comments_published_count,exemplar_accepted_count_total30,exemplar_accepted_count_total7,exemplar_accepted_count_total90,exemplar_returned_count_total30,exemplar_returned_count_total7,exemplar_returned_count_total90,exemplar_returned_value_total30,exemplar_returned_value_total7,exemplar_returned_value_total90,...,img_emb_2038,img_emb_2039,img_emb_2040,img_emb_2041,img_emb_2042,img_emb_2043,img_emb_2044,img_emb_2045,img_emb_2046,img_emb_2047
84331,0.0,1401.0,255.0,3930.0,83.0,18.0,216.0,1234.398811,1095.527345,1320.937040,...,0.678911,0.201299,0.064769,0.024806,0.060782,0.037871,0.288053,0.017216,0.044656,0.261535
159526,0.0,3123.0,561.0,9893.0,254.0,57.0,633.0,1277.155890,1136.731404,1374.119216,...,1.010675,0.471715,0.018562,1.592575,0.083084,0.014491,0.094282,0.016304,1.283071,0.826721
211353,0.0,65.0,28.0,133.0,0.0,0.0,2.0,0.000000,0.000000,745.042368,...,0.329278,0.115866,0.000669,0.185069,0.063794,0.284358,0.055890,0.065554,0.043575,0.128025

In [14]:
comb_test = multimodal.transform(test_df)
comb_test.head(3)

Извлечение эмбеддингов для 2500 текстов...

Batches:   0%|          | 0/20 [00:00<?, ?it/s]

Получены эмбеддинги: (2500, 384)
...Извлечение признаков из изображений...

Batches:   0%|          | 0/157 [00:00<?, ?it/s]

Извлечено 2500 признаков размерностью 2048
Извлечены признаки: (2500, 2472)

,comments_published_count,exemplar_accepted_count_total30,exemplar_accepted_count_total7,exemplar_accepted_count_total90,exemplar_returned_count_total30,exemplar_returned_count_total7,exemplar_returned_count_total90,exemplar_returned_value_total30,exemplar_returned_value_total7,exemplar_returned_value_total90,...,img_emb_2038,img_emb_2039,img_emb_2040,img_emb_2041,img_emb_2042,img_emb_2043,img_emb_2044,img_emb_2045,img_emb_2046,img_emb_2047
63782,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,...,0.092743,0.190114,0.000000,0.896840,0.776192,0.117221,0.305830,0.180983,0.063902,1.056367
4533,0.0,860.0,246.0,2308.0,36.0,9.0,99.0,1195.540614,1032.930978,1305.306955,...,0.750833,0.089819,0.156811,0.206776,1.087665,0.068027,0.043237,0.598829,1.399496,0.857461
169759,0.0,404.0,65.0,1031.0,4.0,1.0,15.0,713.900842,586.389324,824.632170,...,1.123625,0.347190,0.898974,0.705725,0.016721,0.171066,0.655469,0.030889,0.488578,0.636142

- Получаем список категориальных фич

In [15]:
cat_features = multimodal.get_features()['Category']
cat_features

['item_count_returns7',
 'item_count_fake_returns7',
 'rating_3_count',
 'has_description',
 'rating_2_count',
 'rating_1_count',
 'item_count_fake_returns30',
 'rating_4_count',
 'item_count_fake_returns90',
 'item_count_returns30',
 'item_count_returns90',
 'videos_published_count',
 'has_image',
 'item_count_sales7']

## Обучение модели

In [83]:
model = MultiModalClassifier('catboost', cat_features)
model

MultiModalClassifier(cat_features=['item_count_returns7',
                                   'item_count_fake_returns7', 'rating_3_count',
                                   'has_description', 'rating_2_count',
                                   'rating_1_count',
                                   'item_count_fake_returns30',
                                   'rating_4_count',
                                   'item_count_fake_returns90',
                                   'item_count_returns30',
                                   'item_count_returns90',
                                   'videos_published_count', 'has_image',
                                   'item_count_sales7'],
                     model_params={})

In [84]:
model.fit(comb_train, y_train, comb_val, y_val)

0:	learn: 0.6809885	test: 0.6813558	best: 0.6813558 (0)	total: 195ms	remaining: 1m 37s
1:	learn: 0.6670242	test: 0.6687004	best: 0.6687004 (1)	total: 394ms	remaining: 1m 38s
2:	learn: 0.6571688	test: 0.6598572	best: 0.6598572 (2)	total: 598ms	remaining: 1m 39s
3:	learn: 0.6451235	test: 0.6476640	best: 0.6476640 (3)	total: 795ms	remaining: 1m 38s
4:	learn: 0.6340303	test: 0.6392425	best: 0.6392425 (4)	total: 1.04s	remaining: 1m 42s
5:	learn: 0.6250248	test: 0.6323122	best: 0.6323122 (5)	total: 1.22s	remaining: 1m 40s
6:	learn: 0.6117911	test: 0.6198932	best: 0.6198932 (6)	total: 1.43s	remaining: 1m 40s
7:	learn: 0.6022886	test: 0.6127638	best: 0.6127638 (7)	total: 1.61s	remaining: 1m 39s
8:	learn: 0.5919843	test: 0.6037965	best: 0.6037965 (8)	total: 1.8s	remaining: 1m 38s
9:	learn: 0.5824369	test: 0.5957920	best: 0.5957920 (9)	total: 1.98s	remaining: 1m 37s
10:	learn: 0.5747631	test: 0.5910751	best: 0.5910751 (10)	total: 2.17s	remaining: 1m 36s
11:	learn: 0.5678209	test: 0.5857217	best: 0.5857217 (11)	total: 2.36s	remaining: 1m 35s
12:	learn: 0.5591193	test: 0.5810505	best: 0.5810505 (12)	total: 2.55s	remaining: 1m 35s
13:	learn: 0.5494301	test: 0.5770980	best: 0.5770980 (13)	total: 2.73s	remaining: 1m 34s
14:	learn: 0.5437675	test: 0.5728901	best: 0.5728901 (14)	total: 2.91s	remaining: 1m 34s
15:	learn: 0.5346097	test: 0.5650739	best: 0.5650739 (15)	total: 3.11s	remaining: 1m 34s
16:	learn: 0.5282535	test: 0.5609297	best: 0.5609297 (16)	total: 3.31s	remaining: 1m 33s
17:	learn: 0.5209708	test: 0.5562133	best: 0.5562133 (17)	total: 3.52s	remaining: 1m 34s
18:	learn: 0.5146489	test: 0.5524576	best: 0.5524576 (18)	total: 3.71s	remaining: 1m 33s
19:	learn: 0.5111325	test: 0.5512110	best: 0.5512110 (19)	total: 3.89s	remaining: 1m 33s
20:	learn: 0.5052983	test: 0.5470765	best: 0.5470765 (20)	total: 4.08s	remaining: 1m 33s
21:	learn: 0.4996445	test: 0.5431717	best: 0.5431717 (21)	total: 4.26s	remaining: 1m 32s
22:	learn: 0.4957534	test: 0.5408857	best: 0.5408857 (22)	total: 4.44s	remaining: 1m 32s
23:	learn: 0.4920625	test: 0.5383080	best: 0.5383080 (23)	total: 4.63s	remaining: 1m 31s
24:	learn: 0.4893054	test: 0.5372577	best: 0.5372577 (24)	total: 4.8s	remaining: 1m 31s
25:	learn: 0.4837076	test: 0.5334840	best: 0.5334840 (25)	total: 4.99s	remaining: 1m 30s
26:	learn: 0.4799759	test: 0.5298502	best: 0.5298502 (26)	total: 5.16s	remaining: 1m 30s
27:	learn: 0.4759495	test: 0.5274531	best: 0.5274531 (27)	total: 5.35s	remaining: 1m 30s
28:	learn: 0.4716372	test: 0.5250676	best: 0.5250676 (28)	total: 5.53s	remaining: 1m 29s
29:	learn: 0.4665699	test: 0.5212275	best: 0.5212275 (29)	total: 5.71s	remaining: 1m 29s
30:	learn: 0.4626515	test: 0.5191901	best: 0.5191901 (30)	total: 5.88s	remaining: 1m 28s
31:	learn: 0.4595331	test: 0.5163751	best: 0.5163751 (31)	total: 6.06s	remaining: 1m 28s
32:	learn: 0.4551894	test: 0.5127333	best: 0.5127333 (32)	total: 6.24s	remaining: 1m 28s
33:	learn: 0.4513789	test: 0.5111645	best: 0.5111645 (33)	total: 6.42s	remaining: 1m 27s
34:	learn: 0.4461493	test: 0.5080267	best: 0.5080267 (34)	total: 6.59s	remaining: 1m 27s
35:	learn: 0.4429972	test: 0.5055274	best: 0.5055274 (35)	total: 6.77s	remaining: 1m 27s
36:	learn: 0.4397644	test: 0.5025706	best: 0.5025706 (36)	total: 6.95s	remaining: 1m 26s
37:	learn: 0.4372580	test: 0.5017192	best: 0.5017192 (37)	total: 7.13s	remaining: 1m 26s
38:	learn: 0.4343533	test: 0.5011540	best: 0.5011540 (38)	total: 7.31s	remaining: 1m 26s
39:	learn: 0.4320084	test: 0.4997924	best: 0.4997924 (39)	total: 7.5s	remaining: 1m 26s
40:	learn: 0.4297140	test: 0.4988640	best: 0.4988640 (40)	total: 7.67s	remaining: 1m 25s
41:	learn: 0.4273879	test: 0.4974856	best: 0.4974856 (41)	total: 7.85s	remaining: 1m 25s
42:	learn: 0.4228920	test: 0.4953036	best: 0.4953036 (42)	total: 8.03s	remaining: 1m 25s
43:	learn: 0.4198711	test: 0.4943600	best: 0.4943600 (43)	total: 8.21s	remaining: 1m 25s
44:	learn: 0.4170096	test: 0.4941801	best: 0.4941801 (44)	total: 8.39s	remaining: 1m 24s
45:	learn: 0.4133421	test: 0.4914423	best: 0.4914423 (45)	total: 8.57s	remaining: 1m 24s
46:	learn: 0.4114259	test: 0.4899696	best: 0.4899696 (46)	total: 8.74s	remaining: 1m 24s
47:	learn: 0.4092054	test: 0.4896170	best: 0.4896170 (47)	total: 8.92s	remaining: 1m 24s
48:	learn: 0.4068141	test: 0.4883155	best: 0.4883155 (48)	total: 9.1s	remaining: 1m 23s
49:	learn: 0.4046906	test: 0.4870628	best: 0.4870628 (49)	total: 9.28s	remaining: 1m 23s
50:	learn: 0.4014865	test: 0.4841597	best: 0.4841597 (50)	total: 9.46s	remaining: 1m 23s
51:	learn: 0.3996908	test: 0.4831836	best: 0.4831836 (51)	total: 9.64s	remaining: 1m 23s
52:	learn: 0.3973825	test: 0.4821427	best: 0.4821427 (52)	total: 9.82s	remaining: 1m 22s
53:	learn: 0.3952455	test: 0.4821530	best: 0.4821427 (52)	total: 10s	remaining: 1m 22s
54:	learn: 0.3915943	test: 0.4793794	best: 0.4793794 (54)	total: 10.2s	remaining: 1m 22s
55:	learn: 0.3891837	test: 0.4782024	best: 0.4782024 (55)	total: 10.4s	remaining: 1m 22s
56:	learn: 0.3865220	test: 0.4782911	best: 0.4782024 (55)	total: 10.5s	remaining: 1m 21s
57:	learn: 0.3845754	test: 0.4778498	best: 0.4778498 (57)	total: 10.7s	remaining: 1m 21s
58:	learn: 0.3822330	test: 0.4767884	best: 0.4767884 (58)	total: 10.9s	remaining: 1m 21s
59:	learn: 0.3796905	test: 0.4763894	best: 0.4763894 (59)	total: 11.1s	remaining: 1m 21s
60:	learn: 0.3771369	test: 0.4753388	best: 0.4753388 (60)	total: 11.2s	remaining: 1m 20s
61:	learn: 0.3750023	test: 0.4742593	best: 0.4742593 (61)	total: 11.4s	remaining: 1m 20s
62:	learn: 0.3732599	test: 0.4739267	best: 0.4739267 (62)	total: 11.7s	remaining: 1m 21s
63:	learn: 0.3714963	test: 0.4732585	best: 0.4732585 (63)	total: 11.9s	remaining: 1m 20s
64:	learn: 0.3695002	test: 0.4722424	best: 0.4722424 (64)	total: 12.1s	remaining: 1m 20s
65:	learn: 0.3677527	test: 0.4710793	best: 0.4710793 (65)	total: 12.2s	remaining: 1m 20s
66:	learn: 0.3653327	test: 0.4708986	best: 0.4708986 (66)	total: 12.4s	remaining: 1m 20s
67:	learn: 0.3632314	test: 0.4701525	best: 0.4701525 (67)	total: 12.6s	remaining: 1m 20s
68:	learn: 0.3611725	test: 0.4693998	best: 0.4693998 (68)	total: 12.8s	remaining: 1m 19s
69:	learn: 0.3595871	test: 0.4692470	best: 0.4692470 (69)	total: 13s	remaining: 1m 19s
70:	learn: 0.3569935	test: 0.4676174	best: 0.4676174 (70)	total: 13.1s	remaining: 1m 19s
71:	learn: 0.3553225	test: 0.4671188	best: 0.4671188 (71)	total: 13.3s	remaining: 1m 19s
72:	learn: 0.3534405	test: 0.4666278	best: 0.4666278 (72)	total: 13.5s	remaining: 1m 18s
73:	learn: 0.3510218	test: 0.4661396	best: 0.4661396 (73)	total: 13.7s	remaining: 1m 18s
74:	learn: 0.3498120	test: 0.4653583	best: 0.4653583 (74)	total: 13.8s	remaining: 1m 18s
75:	learn: 0.3480314	test: 0.4644919	best: 0.4644919 (75)	total: 14s	remaining: 1m 18s
76:	learn: 0.3458591	test: 0.4639968	best: 0.4639968 (76)	total: 14.2s	remaining: 1m 17s
77:	learn: 0.3442166	test: 0.4638118	best: 0.4638118 (77)	total: 14.4s	remaining: 1m 17s
78:	learn: 0.3419445	test: 0.4632203	best: 0.4632203 (78)	total: 14.5s	remaining: 1m 17s
79:	learn: 0.3404464	test: 0.4628544	best: 0.4628544 (79)	total: 14.7s	remaining: 1m 17s
80:	learn: 0.3396137	test: 0.4625853	best: 0.4625853 (80)	total: 14.9s	remaining: 1m 17s
81:	learn: 0.3364569	test: 0.4604350	best: 0.4604350 (81)	total: 15.1s	remaining: 1m 16s
82:	learn: 0.3343334	test: 0.4595444	best: 0.4595444 (82)	total: 15.3s	remaining: 1m 16s
83:	learn: 0.3330053	test: 0.4593492	best: 0.4593492 (83)	total: 15.4s	remaining: 1m 16s
84:	learn: 0.3316187	test: 0.4595080	best: 0.4593492 (83)	total: 15.6s	remaining: 1m 16s
85:	learn: 0.3286165	test: 0.4595851	best: 0.4593492 (83)	total: 15.8s	remaining: 1m 16s
86:	learn: 0.3266970	test: 0.4587958	best: 0.4587958 (86)	total: 16s	remaining: 1m 15s
87:	learn: 0.3245344	test: 0.4573426	best: 0.4573426 (87)	total: 16.2s	remaining: 1m 15s
88:	learn: 0.3224707	test: 0.4582715	best: 0.4573426 (87)	total: 16.3s	remaining: 1m 15s
89:	learn: 0.3209140	test: 0.4579231	best: 0.4573426 (87)	total: 16.5s	remaining: 1m 15s
90:	learn: 0.3197808	test: 0.4573730	best: 0.4573426 (87)	total: 16.7s	remaining: 1m 15s
91:	learn: 0.3183384	test: 0.4578158	best: 0.4573426 (87)	total: 16.9s	remaining: 1m 14s
92:	learn: 0.3158864	test: 0.4565257	best: 0.4565257 (92)	total: 17s	remaining: 1m 14s
93:	learn: 0.3142851	test: 0.4563799	best: 0.4563799 (93)	total: 17.2s	remaining: 1m 14s
94:	learn: 0.3128567	test: 0.4561757	best: 0.4561757 (94)	total: 17.5s	remaining: 1m 14s
95:	learn: 0.3110625	test: 0.4557659	best: 0.4557659 (95)	total: 17.6s	remaining: 1m 14s
96:	learn: 0.3094262	test: 0.4549261	best: 0.4549261 (96)	total: 17.8s	remaining: 1m 13s
97:	learn: 0.3081859	test: 0.4549956	best: 0.4549261 (96)	total: 18s	remaining: 1m 13s
98:	learn: 0.3064861	test: 0.4541858	best: 0.4541858 (98)	total: 18.2s	remaining: 1m 13s
99:	learn: 0.3056577	test: 0.4534822	best: 0.4534822 (99)	total: 18.4s	remaining: 1m 13s
100:	learn: 0.3041898	test: 0.4528870	best: 0.4528870 (100)	total: 18.6s	remaining: 1m 13s
101:	learn: 0.3031061	test: 0.4529168	best: 0.4528870 (100)	total: 18.9s	remaining: 1m 13s
102:	learn: 0.3020062	test: 0.4530860	best: 0.4528870 (100)	total: 19.1s	remaining: 1m 13s
103:	learn: 0.3003038	test: 0.4532514	best: 0.4528870 (100)	total: 19.3s	remaining: 1m 13s
104:	learn: 0.2995700	test: 0.4527916	best: 0.4527916 (104)	total: 19.5s	remaining: 1m 13s
105:	learn: 0.2984117	test: 0.4523715	best: 0.4523715 (105)	total: 19.7s	remaining: 1m 13s
106:	learn: 0.2966202	test: 0.4520296	best: 0.4520296 (106)	total: 19.9s	remaining: 1m 12s
107:	learn: 0.2950108	test: 0.4511234	best: 0.4511234 (107)	total: 20.1s	remaining: 1m 12s
108:	learn: 0.2939694	test: 0.4510538	best: 0.4510538 (108)	total: 20.2s	remaining: 1m 12s
109:	learn: 0.2925090	test: 0.4505842	best: 0.4505842 (109)	total: 20.5s	remaining: 1m 12s
110:	learn: 0.2908862	test: 0.4503055	best: 0.4503055 (110)	total: 20.7s	remaining: 1m 12s
111:	learn: 0.2896343	test: 0.4498225	best: 0.4498225 (111)	total: 20.9s	remaining: 1m 12s
112:	learn: 0.2883220	test: 0.4507079	best: 0.4498225 (111)	total: 21.1s	remaining: 1m 12s
113:	learn: 0.2872916	test: 0.4502562	best: 0.4498225 (111)	total: 21.3s	remaining: 1m 12s
114:	learn: 0.2859515	test: 0.4501211	best: 0.4498225 (111)	total: 21.5s	remaining: 1m 11s
115:	learn: 0.2840076	test: 0.4504656	best: 0.4498225 (111)	total: 21.7s	remaining: 1m 11s
116:	learn: 0.2830263	test: 0.4503022	best: 0.4498225 (111)	total: 21.9s	remaining: 1m 11s
117:	learn: 0.2819030	test: 0.4504157	best: 0.4498225 (111)	total: 22s	remaining: 1m 11s
118:	learn: 0.2804684	test: 0.4503228	best: 0.4498225 (111)	total: 22.2s	remaining: 1m 11s
119:	learn: 0.2787877	test: 0.4497431	best: 0.4497431 (119)	total: 22.4s	remaining: 1m 10s
120:	learn: 0.2764381	test: 0.4501032	best: 0.4497431 (119)	total: 22.6s	remaining: 1m 10s
121:	learn: 0.2752689	test: 0.4496618	best: 0.4496618 (121)	total: 22.7s	remaining: 1m 10s
122:	learn: 0.2739429	test: 0.4496516	best: 0.4496516 (122)	total: 22.9s	remaining: 1m 10s
123:	learn: 0.2730316	test: 0.4493383	best: 0.4493383 (123)	total: 23.1s	remaining: 1m 10s
124:	learn: 0.2715989	test: 0.4493256	best: 0.4493256 (124)	total: 23.4s	remaining: 1m 10s
125:	learn: 0.2706337	test: 0.4491838	best: 0.4491838 (125)	total: 23.5s	remaining: 1m 9s
126:	learn: 0.2690265	test: 0.4484674	best: 0.4484674 (126)	total: 23.7s	remaining: 1m 9s
127:	learn: 0.2683485	test: 0.4493286	best: 0.4484674 (126)	total: 23.9s	remaining: 1m 9s
128:	learn: 0.2670194	test: 0.4490118	best: 0.4484674 (126)	total: 24.1s	remaining: 1m 9s
129:	learn: 0.2659834	test: 0.4491503	best: 0.4484674 (126)	total: 24.2s	remaining: 1m 9s
130:	learn: 0.2648329	test: 0.4489267	best: 0.4484674 (126)	total: 24.4s	remaining: 1m 8s
131:	learn: 0.2638272	test: 0.4490959	best: 0.4484674 (126)	total: 24.6s	remaining: 1m 8s
132:	learn: 0.2624935	test: 0.4490679	best: 0.4484674 (126)	total: 24.8s	remaining: 1m 8s
133:	learn: 0.2607070	test: 0.4490968	best: 0.4484674 (126)	total: 25s	remaining: 1m 8s
134:	learn: 0.2593428	test: 0.4484644	best: 0.4484644 (134)	total: 25.1s	remaining: 1m 7s
135:	learn: 0.2577625	test: 0.4483618	best: 0.4483618 (135)	total: 25.3s	remaining: 1m 7s
136:	learn: 0.2560966	test: 0.4479615	best: 0.4479615 (136)	total: 25.5s	remaining: 1m 7s
137:	learn: 0.2551028	test: 0.4476695	best: 0.4476695 (137)	total: 25.7s	remaining: 1m 7s
138:	learn: 0.2540281	test: 0.4479129	best: 0.4476695 (137)	total: 25.8s	remaining: 1m 7s
139:	learn: 0.2529877	test: 0.4480753	best: 0.4476695 (137)	total: 26s	remaining: 1m 6s
140:	learn: 0.2515193	test: 0.4484006	best: 0.4476695 (137)	total: 26.2s	remaining: 1m 6s
141:	learn: 0.2507820	test: 0.4488612	best: 0.4476695 (137)	total: 26.4s	remaining: 1m 6s
142:	learn: 0.2496503	test: 0.4488382	best: 0.4476695 (137)	total: 26.6s	remaining: 1m 6s
143:	learn: 0.2487227	test: 0.4482567	best: 0.4476695 (137)	total: 26.7s	remaining: 1m 6s
144:	learn: 0.2477320	test: 0.4480678	best: 0.4476695 (137)	total: 26.9s	remaining: 1m 5s
145:	learn: 0.2464563	test: 0.4488672	best: 0.4476695 (137)	total: 27.1s	remaining: 1m 5s
146:	learn: 0.2453450	test: 0.4497722	best: 0.4476695 (137)	total: 27.3s	remaining: 1m 5s
147:	learn: 0.2438177	test: 0.4491779	best: 0.4476695 (137)	total: 27.5s	remaining: 1m 5s
148:	learn: 0.2421149	test: 0.4497481	best: 0.4476695 (137)	total: 27.6s	remaining: 1m 5s
149:	learn: 0.2409491	test: 0.4497997	best: 0.4476695 (137)	total: 27.8s	remaining: 1m 4s
150:	learn: 0.2396339	test: 0.4497600	best: 0.4476695 (137)	total: 28s	remaining: 1m 4s
151:	learn: 0.2387146	test: 0.4501517	best: 0.4476695 (137)	total: 28.2s	remaining: 1m 4s
152:	learn: 0.2376937	test: 0.4501482	best: 0.4476695 (137)	total: 28.4s	remaining: 1m 4s
153:	learn: 0.2363664	test: 0.4500479	best: 0.4476695 (137)	total: 28.6s	remaining: 1m 4s
154:	learn: 0.2351688	test: 0.4490364	best: 0.4476695 (137)	total: 28.8s	remaining: 1m 4s
155:	learn: 0.2340594	test: 0.4490126	best: 0.4476695 (137)	total: 29s	remaining: 1m 3s
156:	learn: 0.2332188	test: 0.4485904	best: 0.4476695 (137)	total: 29.2s	remaining: 1m 3s
157:	learn: 0.2318915	test: 0.4493632	best: 0.4476695 (137)	total: 29.4s	remaining: 1m 3s
158:	learn: 0.2310251	test: 0.4491272	best: 0.4476695 (137)	total: 29.6s	remaining: 1m 3s
159:	learn: 0.2303099	test: 0.4493323	best: 0.4476695 (137)	total: 29.8s	remaining: 1m 3s
160:	learn: 0.2293495	test: 0.4497109	best: 0.4476695 (137)	total: 30.1s	remaining: 1m 3s
161:	learn: 0.2278618	test: 0.4494682	best: 0.4476695 (137)	total: 30.3s	remaining: 1m 3s
162:	learn: 0.2266217	test: 0.4499734	best: 0.4476695 (137)	total: 30.6s	remaining: 1m 3s
163:	learn: 0.2249040	test: 0.4531909	best: 0.4476695 (137)	total: 30.8s	remaining: 1m 3s
164:	learn: 0.2234942	test: 0.4522587	best: 0.4476695 (137)	total: 31s	remaining: 1m 2s
165:	learn: 0.2224998	test: 0.4525383	best: 0.4476695 (137)	total: 31.2s	remaining: 1m 2s
166:	learn: 0.2207478	test: 0.4509246	best: 0.4476695 (137)	total: 31.4s	remaining: 1m 2s
167:	learn: 0.2193847	test: 0.4511448	best: 0.4476695 (137)	total: 31.6s	remaining: 1m 2s
168:	learn: 0.2181325	test: 0.4502196	best: 0.4476695 (137)	total: 31.8s	remaining: 1m 2s
169:	learn: 0.2164602	test: 0.4498720	best: 0.4476695 (137)	total: 32s	remaining: 1m 2s
170:	learn: 0.2153264	test: 0.4501729	best: 0.4476695 (137)	total: 32.2s	remaining: 1m 1s
171:	learn: 0.2144492	test: 0.4501927	best: 0.4476695 (137)	total: 32.4s	remaining: 1m 1s
172:	learn: 0.2129001	test: 0.4503765	best: 0.4476695 (137)	total: 32.6s	remaining: 1m 1s
173:	learn: 0.2113871	test: 0.4502835	best: 0.4476695 (137)	total: 32.8s	remaining: 1m 1s
174:	learn: 0.2095238	test: 0.4503472	best: 0.4476695 (137)	total: 33.1s	remaining: 1m 1s
175:	learn: 0.2084715	test: 0.4496089	best: 0.4476695 (137)	total: 33.3s	remaining: 1m 1s
176:	learn: 0.2070808	test: 0.4506402	best: 0.4476695 (137)	total: 33.5s	remaining: 1m 1s
177:	learn: 0.2060627	test: 0.4508700	best: 0.4476695 (137)	total: 33.7s	remaining: 1m
178:	learn: 0.2047360	test: 0.4502479	best: 0.4476695 (137)	total: 33.9s	remaining: 1m
179:	learn: 0.2036736	test: 0.4511114	best: 0.4476695 (137)	total: 34.1s	remaining: 1m
180:	learn: 0.2024159	test: 0.4502925	best: 0.4476695 (137)	total: 34.3s	remaining: 1m
181:	learn: 0.2013548	test: 0.4505738	best: 0.4476695 (137)	total: 34.5s	remaining: 1m
182:	learn: 0.1995893	test: 0.4505895	best: 0.4476695 (137)	total: 34.8s	remaining: 1m
183:	learn: 0.1979076	test: 0.4501437	best: 0.4476695 (137)	total: 35s	remaining: 1m
184:	learn: 0.1966352	test: 0.4499009	best: 0.4476695 (137)	total: 35.2s	remaining: 59.9s
185:	learn: 0.1954695	test: 0.4501607	best: 0.4476695 (137)	total: 35.4s	remaining: 59.7s
186:	learn: 0.1938150	test: 0.4510672	best: 0.4476695 (137)	total: 35.7s	remaining: 59.7s
187:	learn: 0.1925921	test: 0.4524603	best: 0.4476695 (137)	total: 35.9s	remaining: 59.6s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 0.4476695115
bestIteration = 137

Shrink model to first 138 iterations.

In [85]:
y_pred = model.predict(comb_test)

In [86]:
f1_score(y_test, y_pred)

0.45348837209302323

In [97]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.96      0.96      0.96      2335
           1       0.44      0.47      0.45       165

    accuracy                           0.92      2500
   macro avg       0.70      0.71      0.71      2500
weighted avg       0.93      0.92      0.93      2500

In [88]:
print("Train target distribution:", pd.DataFrame(y_train).value_counts())
print("Val target distribution:", pd.DataFrame(y_val).value_counts()) 
print("Test target distribution:", pd.DataFrame(y_test).value_counts())

Train target distribution: 0
0    4669
1     331
Name: count, dtype: int64
Val target distribution: 0
0    2335
1     165
Name: count, dtype: int64
Test target distribution: 0
0    2335
1     165
Name: count, dtype: int64

In [89]:
probas = model.predict_proba(comb_test)
print("Probabilities for class 1:")
print(pd.Series(probas[:, 1]).describe())

Probabilities for class 1:
count    2500.000000
mean        0.238582
std         0.199264
min         0.010000
25%         0.087979
50%         0.169232
75%         0.335532
max         0.947836
dtype: float64

In [90]:
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
print(f"False Positives: {fp}, True Positives: {tp}")

False Positives: 101, True Positives: 78

In [94]:
model.tune_threshold(comb_val, y_val)

Оптимальный порог: 0.609

np.float64(0.609090909090909)